name = "DifferentialPhaseContrast"
uuid = "4f2186bb-3a2c-44f0-a062-04c6d4d3fd0d"
authors = ["Ewout van der veer"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[targets]
test = ["Test", "Random", "DelimitedFiles"]
